spring.application.name=api-gateway

server.port=8080

#Api Gateway routes

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# User Service
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

# Monitoring Service
spring.cloud.gateway.server.webflux.routes[2].id=monitoring-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://monitoring-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/monitoring/**

# Alert Service
spring.cloud.gateway.server.webflux.routes[3].id=alert-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://alert-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/alerts/**

# Cost Service
spring.cloud.gateway.server.webflux.routes[4].id=cost-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://cost-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/cost/**

# Report Service
spring.cloud.gateway.server.webflux.routes[5].id=report-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://report-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/reports/**



# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
